makeTRash: command_ls.c history.c directoryMovements.c command_fgbg.c terminalDisp.c rawMode.c redirection.c main.c
	gcc command_ls.c history.c directoryMovements.c command_fgbg.c terminalDisp.c rawMode.c redirection.c main.c -o makeTRash
